server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/babytun?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    port: 6379
    password: 123456
    database: 3
    host: localhost
    # 配置rabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
